config/routes.rb
MovieQueue::Application.routes.draw do
  match 'notifications/poll' => 'notifications#poll'
  match 'notifications/:id/read' => 'notifications#read'
  resources :movies do
    resources :downloads
    resources :torrents
  end

  root :to => 'movies#index'
  match 'movielist.json' => 'movies#list'
  match 'torrent_list.json' => 'torrents#list'
  match 'movie/:id/download' => 'movies#download'
  match 'movie/:m_id/fetch_torrents' => 'torrents#list'
  match 'whoami' => 'movies#test'

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  # GET /movies
  # GET /movies.json
  def list
    query = params[:q] || params[:term]
    @movies = Movie.get_movie_list(query)
    render json: @movies 
  end

  def get
    Movie.enqueue_all
  end

  def index
    @movies = []
    @movies << Movie.ready
    @movies << Movie.downloading.sort_by { |m| -(m.download.percent_done) }
    @movies << Movie.queued
    @movies = @movies.flatten

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @movies }
    end
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
    @movie = Movie.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @movie }
    end
  end

  # GET /movies/new
  # GET /movies/new.json
  def new
    @movie = Movie.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @movie }
    end
  end

  # GET /movies/1/edit
  def edit
    @movie = Movie.find(params[:id])
  end

  def download
    @movie = Movie.find(params[:id])
    Resque.enqueue(Movie, @movie.id)
    render :text => "Ok"
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = Movie.new(params[:movie])
    respond_to do |format|
      if @movie.save
        Resque.enqueue(Movie, @movie.id, params[:movie][:name])
        Resque.enqueue(Torrent, @movie.id, @movie.search_term, :all, false)
        format.html { redirect_to edit_movie_url @movie }
      else
        format.html { render action: "new" }
      end
    end
  end

  # PUT /movies/1
  # PUT /movies/1.json
  def update
    @movie = Movie.find(params[:id])
    api_search_term = params[:movie][:name]

    if(api_search_term)
      @movie.update_from_api(api_search_term)
      Notification.create(:notification => "Updated '#{@movie.search_term}' information using rotten tomatoes.")
    end

    respond_to do |format|
      if @movie.update_attributes(params[:movie])
        Resque.enqueue(Movie, @movie.id)
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy

    respond_to do |format|
      format.html { redirect_to movies_url }
      format.json { head :ok }
    end
  end

  def test
    render :text => `whoami`
  end

end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/movies/_form.html.erb
<%= form_for(@movie) do |f| %>
    <p id="notice"><%= notice %></p>
    <% if @movie.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@movie.errors.count, "error") %> prohibited this movie from being saved:</h2>
          <ul>
            <% @movie.errors.full_messages.each do |msg|
            %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.text_field :search_term %><%= submit_tag "Search", :name => "rtfetch", :id => "rtfetch" %>
      <img src="/assets/ajax-loader.gif" id="ajax_loader"/>
    </div>

    <div class="field" id="movie_list" style="display:none">
      <%= f.label :name %>
      <br/>
      <%= f.select(:name, ['Enter your query to get a list of movies'], {}, :disabled => true) %><%= f.submit %>
    </div>
<% end %>

app/views/movies/edit.html.erb
<h1>Editing movie</h1>

<script type="text/javascript">
$(document).ready(function() {
    console.debug(parent, window, $.fancybox)
    if(parent != window) {
        parent.window.location.reload( false )
//        parent.$.fancybox.close();
    } else {
        console.debug("no fancybox detected.")
    }
  })
</script>

<%= render 'form' %>

<% if(@movie.torrents.size == 0) %>

<%= form_for(@movie, :url => "/movie/#{@movie.id}/fetch_torrents") do |f| %>
    <div class="actions" id="torrent_list">
      <%= f.submit "Fetch torrent list" %>
    </div>
<% end %>

<% else %>
    <%= link_to "View Torrents", movie_torrents_path(@movie) %>

<% end %>
<td><%= link_to image_tag("/assets/ex.png", :border=>0), @movie, confirm: 'Are you sure?', method: :delete %></td>
<td><%= link_to image_tag("/assets/download.png", :border=>0), movie_torrents_path(@movie) %></td>

app/views/movies/index.html.erb
<%# TODO: Scope out the names to the appropriate tables %>
<%# TODO: Check movie release date after adding (add to resque queue) %>
<p id="notice"><%= notice %></p>
<script type="text/javascript">

    $('.movies.index').ready(function() {
        queryNotifications()

        setInterval(function() {
            queryNotifications()
        }, 5000)
    });
</script>
<h1 style="padding-left: 4em;">Movie Queue</h1>
<%= link_to '+', new_movie_path, :class => "plus add_movie" %><%= link_to 'Movie', new_movie_path, :class => "add_movie", :id => "add_movie" %>
<br/>
<br/>
<div style="clear: both;"></div>
<% @movies.each do |movie| %>

    <div style="float: left; margin: 10px; height: 150px; overflow: hidden;" class="movie_info" data-id="<%= movie.id %>" data-title="<%= movie.name %>">
      <%= link_to image_tag(movie.movie_cover_path, { :width => '125px' }), edit_movie_path(movie) %>
    </div>
<% end %>
<div style="clear: both;"></div>

app/views/movies/new.html.erb
<div class="movies create">

<%= render 'form' %>
</div>

app/views/movies/show.html.erb
<div class="movies show">
<% if @movie.api_queried.nil? %>
    <strong>Fetching Information from Rotten Tomatoes...</strong>
<% else %>


<% if @movie.download.present? %>
  <div class="status_bar large">
    <div class="progress" style="width: <%= @movie.percent_complete %>%"></div>
  </div>
<% end %>
  <div class="rating"><%= image_tag @movie.rt_image %><%= @movie.critics_score %>%</div>
  <div class="rating"><%= image_tag @movie.meta_image %><%= @movie.audience_score %>%</div>

  <table>
    <tr>
      <th>Running Time</th>
      <th>Year</th>
<% if @movie.download.present? %>
      <th>Filesize</th>
      <th>ETA:</th>
<% end %>
    </tr>
    <tr>
      <td><%= @movie.display_runtime %></td>
      <td><%= @movie.year %></td>
<% if @movie.download.present? %>
      <td><%= @movie.display_filesize %></td>
      <td><%= @movie.display_eta %></td>
<% end %>
    </tr>
  </table>

<% if @movie.download.nil? && @movie.torrents.present? %>
  <div class="info"><%= link_to "Choose Download", movie_torrents_path(@movie) %></div>
<% elsif @movie.torrents.empty? %>
  <div class="info"><%= link_to "Fetch Torrents", "/movie/#{@movie.id}/fetch_torrents" %></div>
<% end %>
  <div class="info"><%= link_to "Delete", @movie, method: :delete %></div>
  <div class="info"><%= link_to "View on RT", @movie.url %></div>
  <div class="info"><%= image_tag @movie.rating_image %></div>
</div>
<% end %>